### get all blogs
GET http://localhost:3003/api/blogs

### delete a blog with id
DELETE http://localhost:3003/api/blogs/6967625f00069a9ce39fefd5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1bWFuIiwiaWQiOiI2OTQyNmE3YjNjYmZkNGQ1NDJlMmQwYjEiLCJpYXQiOjE3NjU5Njc3ODV9.BO22nCikHUUSoPLsZSJkF6l4gjU2SAj3_t9iSqj6bAY

### update a blog with valid id
PUT http://localhost:3003/api/blogs/69429afadf9a5cf3f0ce8e4a
Content-Type: application/json

{
  "likes": "8",
}

### post a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikh1bWFuIiwiaWQiOiI2OTQyNmE3YjNjYmZkNGQ1NDJlMmQwYjEiLCJpYXQiOjE3NjU5NjA2NTl9.AkED4waiXed9vqvzeUkQXdHLOUx2oG5lhY-mCj1lcJw

{
  "title": "blog 7",
  "author": "Human",
  "url": "www.destroyer.com",
  "likes": 6
}