### get all blogs
GET http://localhost:3003/api/blogs

### delete a blog with id
DELETE http://localhost:3003/api/blogs/69271cd1c48c0d175160d1d7

### update a blog with valid id
PUT http://localhost:3003/api/blogs/692b5effe326933b3f290581
Content-Type: application/json

{
  "title": "this is a updated blog",
  "url": "www.hello.com"
}

### post a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdvcmlsbGEiLCJpZCI6IjY5M2ZmY2Y3OGMyZDUyOWY1NzliYWQ3NCIsImlhdCI6MTc2NTg4ODM0M30.OhAPBWmx1jaElLkSkWSYbZLCFiUTGRpkCy9sxUlHoTI

{
  "title": "Authorization: successful",
  "author": "RZ Rakib",
  "url": "www.example.com",
  "likes": 5
}