### create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

# {
#   "username": "Human",
#   "name": "Destroyer",
#   "password": "r12345"
# }

{
  "username": "Penguin",
  "name": "Ocean blue",
  "password": "r12345"
}


# {
#   "username": "Gorilla",
#   "name": "Amazon Rainforest",
#   "password": "12345"
# }